Hyperparameter:
  batch_size: 1
  learning_rate: 1e-4
  epoch: 300

Type:
  task: train # predict, train. predict is for inference only; train is for training and testing the model.
  save_tag: Null

Model:
  seg_outChans: 1
  dataset : HGG # HGG, LGG
  tumor_type: WT # WT(whole tumor) TC(tumor core) ET(enhancing tumor)